# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sayhello',
                'doc_host': 'https://gdario.github.io',
                'git_url': 'https://github.com/gdario/sayhello',
                'lib_path': 'sayhello'},
  'syms': {'sayhello.core': {'sayhello.core.foo': ('core.html#foo', 'sayhello/core.py')}}}
